; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/MissouriMRDT/RoveComm_Arduino.git#2026
    https://github.com/MissouriMRDT/RoveMotor.git
    https://github.com/MissouriMRDT/RoveControl.git
    https://github.com/MissouriMRDT/SMoCo_Arduino.git#bf57bf301c14674ee6af219410def6d9ea1bd1f9
    https://github.com/MissouriMRDT/RoveSwitch.git
    https://github.com/waas-rent/vesc_can_sdk
